config/routes.rb
Rails.application.routes.draw do
  # namespace :admin do
  # get 'mentors/index'
  # end

  # namespace :admin do
  # get 'mentors/show'
  # end

  # namespace :admin do
  # get 'mentors/new'
  # end

  # namespace :admin do
  # get 'mentors/create'
  # end

  # namespace :admin do
  # get 'mentors/edit'
  # end

  # namespace :admin do
  # get 'mentors/update'
  # end

  # namespace :admin do
  # get 'mentors/archive_mentor'
  # end

  # sessions
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'

  root to: 'pages#index'

  get 'helps/index'

  get 'message_boards/index'

  get 'updates/index'

  get 'resources/index'

  get '/mentors', to: 'mentors#index'

  get 'students/index'

  get 'students/create'

  get 'students/edit'

  get '/home', to: 'pages#index'
  get 'users/new', to: 'users#new'

  resources :cohorts, :users

  namespace :admin do
    resources :users
    resources :cohorts
    resources :groups
    post '/archive/:id', to: 'users#archive_student', as: 'archive'
    get '/getStudentsByGroup/:id', to: 'groups#students_by_group'
  end

  # mentors
  get '/mentors', to: 'mentors#index'

  # get  '/signup',  to: 'users#new'
  # post '/signup', to: 'users#create'

  # students
  resources :posts
  resources :students
  resource :calendar, only: [:show], controller: :calendar
  get 'calendar/show'

  # groups
  get 'groups/index'
  get 'groups/show/:id', to: 'groups#show'

  # Calendar
  # resources :calendar, only: [:show], controller: :calendar
  resources :events

  # workshop
  get 'workshops/index'
  get '/workshops/:id', to: 'workshops#show', as: 'workshop'

  # reset password
  resources :password_resets, only: %i[new update]
end

app/controllers/workshops_controller.rb
class WorkshopsController < ApplicationController
  before_action :set_page_title
  def index
    @workshops = workshop_payload
  end

  def show
    @workshop = workshop_payload.select { |w| w[:id] == params[:id].to_i }.pop 
  end

  private

  def workshop_payload
    [
      {
        id: 1,
        title: 'Workshop 1',
        url: 'http://www.google.com',
        logo: 'workshop.jpg',
        description: 'I am good at containing small bits of information about this workshop.'
      },
      {
        id: 2,
        title: 'Workshop 2',
        url: 'http://www.google.com',
        logo: 'workshop.jpg',
        description: 'I am good at containing small bits of information about this workshop.'
      },
      {
        id: 3,
        title: 'Workshop 3',
        url: 'http://www.google.com',
        logo: 'workshop.jpg',
        description: 'I am good at containing small bits of information about this workshop.'
      },
      {
        id: 4,
        title: 'Workshop 4',
        url: 'http://www.google.com',
        logo: 'workshop.jpg',
        description: 'I am good at containing small bits of information about this workshop.'
      }
    ]
  end

  private

  def set_page_title
    @page_title = 'Workshops and Presentations'
  end

end

app/helpers/workshops_helper.rb
module WorkshopsHelper
end

app/views/workshops/index.html.erb
<div class="row">
    <% @workshops.each do |workshop| %>
        <div class="col s12 m4">
            <div class="card">
                <div class="card-image" style='border-bottom: 1px solid #ccc'>
                    <%= image_tag workshop[:logo], class: 'workshop-logo' %>
                    <%= link_to workshop_path(workshop[:id]), class: "btn-floating halfway-fab waves-effect waves-light blue" do %>
                        <i class="material-icons">arrow_forward</i>
                    <% end %>
                </div>
                <div class="card-content">
                    <span class="card-title workshop-card-title"><%= workshop[:title] %></span>
                    <p><%= workshop[:description] %></p>
                </div>
            </div>
        </div>
    <% end %>
</div>

app/views/workshops/show.html.erb
<%= image_tag @workshop[:logo], class: 'workshop-logo' %>
    <h4>
        <%= @workshop[:title] %>
    </h4>
    <hr/>
    <div class="row">
        <div class="col s12 m4">
            <div class="card blue-grey darken-1">
                <div class="card-content white-text">
                    <span class="card-title">Card Title</span>
                    <p>I am a very simple card. I am good at containing small bits of information. I am convenient because
                        I require little markup to use effectively.</p>
                </div>
                <div class="card-action">
                    <a href="#">This is a link</a>
                </div>
            </div>
        </div>
        <div class="col s12 m4">
            <div class="card blue-grey darken-1">
                <div class="card-content white-text">
                    <span class="card-title">Card Title</span>
                    <p>I am a very simple card. I am good at containing small bits of information. I am convenient because
                        I require little markup to use effectively.</p>
                </div>
                <div class="card-action">
                    <a href="#">This is a link</a>
                </div>
            </div>
        </div>
        <div class="col s12 m4">
            <div class="card blue-grey darken-1">
                <div class="card-content white-text">
                    <span class="card-title">Card Title</span>
                    <p>I am a very simple card. I am good at containing small bits of information. I am convenient because
                        I require little markup to use effectively.</p>
                </div>
                <div class="card-action">
                    <a href="#">This is a link</a>
                </div>
            </div>
        </div>
    </div>