config/routes.rb
Rails.application.routes.draw do
  # namespace :admin do
  # get 'mentors/index'
  # end

  # namespace :admin do
  # get 'mentors/show'
  # end

  # namespace :admin do
  # get 'mentors/new'
  # end

  # namespace :admin do
  # get 'mentors/create'
  # end

  # namespace :admin do
  # get 'mentors/edit'
  # end

  # namespace :admin do
  # get 'mentors/update'
  # end

  # namespace :admin do
  # get 'mentors/archive_mentor'
  # end

  # sessions
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'

  root to: 'pages#index'

  get 'helps/index'

  get 'message_boards/index'

  get 'updates/index'

  get 'resources/index'

  get '/mentors', to: 'mentors#index'

  get 'students/index'

  get 'students/create'

  get 'students/edit'

  get '/home', to: 'pages#index'
  get 'users/new', to: 'users#new'

  resources :cohorts, :users

  namespace :admin do
    resources :users
    resources :cohorts
    resources :groups
    post '/archive/:id', to: 'users#archive_student', as: 'archive'
    get '/getStudentsByGroup/:id', to: 'groups#students_by_group'
  end

  # mentors
  get '/mentors', to: 'mentors#index'

  # get  '/signup',  to: 'users#new'
  # post '/signup', to: 'users#create'

  # students
  resources :posts
  resources :students
  resource :calendar, only: [:show], controller: :calendar
  get 'calendar/show'

  # groups
  get 'groups/index'
  get 'groups/show/:id', to: 'groups#show'

  # Calendar
  # resources :calendar, only: [:show], controller: :calendar
  resources :events

  # workshop
  get 'workshops/index'
  get '/workshops/:id', to: 'workshops#show', as: 'workshop'

  # reset password
  resources :password_resets, only: %i[new update]
end

app/views/layouts/admin/application.html.erb
<!DOCTYPE html>
<html>

<head>
    <title>Graymatter</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application' %>
    <!-- SEO: If your mobile URL is different from the desktop URL, add a canonical link to the desktop page https://developers.google.com/webmasters/smartphone-sites/feature-phones -->
    <!--
    <link rel="canonical" href="http://www.example.com/">
    -->

    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto:regular,bold,italic,thin,light,bolditalic,black,medium&amp;lang=en">
    <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
    <link rel="stylesheet" href="https://code.getmdl.io/1.3.0/material.cyan-light_blue.min.css">

    <%= favicon_link_tag asset_path('brain_logo.png'), :rel => 'icon', :type =>  'image/png' %>

    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet"> 
    
    <script defer src="https://use.fontawesome.com/releases/v5.0.8/js/solid.js" integrity="sha384-+Ga2s7YBbhOD6nie0DzrZpJes+b2K1xkpKxTFFcx59QmVPaSA8c7pycsNaFwUK6l" crossorigin="anonymous"></script>
    <script defer src="https://use.fontawesome.com/releases/v5.0.8/js/fontawesome.js" integrity="sha384-7ox8Q2yzO/uWircfojVuCQOZl+ZZBg2D2J5nkpLqzH1HY0C1dHlTKIbpRz/LG23c" crossorigin="anonymous"></script>

    <style>
        #view-graymatter {
            position: fixed;
            display: block;
            right: 0;
            bottom: 0;
            margin-right: 40px;
            margin-bottom: 40px;
            z-index: 900;
        }
    </style>
</head>

<body>
    <% if logged_in? %>
        <div class="demo-layout mdl-layout mdl-js-layout mdl-layout--fixed-drawer mdl-layout--fixed-header">
        <% else %>
            <div class="demo-layout mdl-layout mdl-js-layout mdl-layout--fixed-header">
            <% end %>
            <% if logged_in? %>
                <header class="demo-header mdl-layout__header mdl-color--blue-grey-900 mdl-color-text--blue-grey-50">
                    <div class="mdl-layout__header-row">
                        <span class="mdl-layout-title">
                            <%= link_to @page_title.upcase %>
                        </span>
                        <div class="mdl-layout-spacer center-align">
                            <%= image_tag 'brain_logo.png', class: 'dashboard-logo' %>
                        </div>
                        <span class="mdl-layout-title right">
                            <%= link_to "Log out", logout_path, method: :delete %>
                        </span>

                        <% if current_user.admin? %>
                            <button class="mdl-button mdl-js-button mdl-js-ripple-effect mdl-button--icon" id="hdrbtn">
                                <i class="material-icons">more_vert</i>
                            </button>

                            <ul class="mdl-menu mdl-js-menu mdl-js-ripple-effect mdl-menu--bottom-right" for="hdrbtn">
                                <li class="mdl-menu__item">Admin Settings</li>
                            </ul>
                        <% end %>
                    </div>
                </header>

                <div class=" mdl-layout__drawer mdl-color--blue-grey-900 mdl-color-text--blue-grey-50">
                    <header class="demo-drawer-header">
                        <%= image_tag 'name-logo.png', class: 'name-dashboard-logo' %>
                        <%= image_tag 'user.jpg', class: 'demo-avatar' %>
                        <div><%= current_user.name.split.map(&:capitalize)*' ' %></div>
                        <div><%= current_user.role.capitalize %></div>
                        <div class="demo-avatar-dropdown" style='margin-top: 10px'>
                            <span>
                                <%= current_user.cohorts.empty? ?
                                    "All Cohorts" :
                                    current_user.cohorts.each { |cohort| cohort.name } %>
                                </span>
                                <div class="mdl-layout-spacer"></div>
                                <!-- I took this out for client review. this serves no purpose
                                <button id="accbtn" class="mdl-button mdl-js-button mdl-js-ripple-effect mdl-button--icon">
                                    <i class="material-icons" role="presentation">arrow_drop_down</i>
                                </button>
                                <ul class="mdl-menu mdl-menu--bottom-right mdl-js-menu mdl-js-ripple-effect" for="accbtn">
                                    <li class="mdl-menu__item">stuff goes here</li>
                                    <li class="mdl-menu__item">stuff goes here</li>
                                </ul>
                                -->
                            </div>
                        </header>
                        <nav class="demo-navigation mdl-navigation mdl-color--blue-grey-800">
                            <%= link_to home_path, class: 'mdl-navigation__link' do %>
                                <i class="mdl-color-text--blue-grey-400 material-icons" role="presentation">home</i>Home</a>
                        <% end %>
                        <%= link_to students_path, class: 'mdl-navigation__link' do %>
                            <i class="mdl-color-text--blue-grey-400 material-icons" role="presentation">face</i>Students</a>
                    <% end %>
                    <%= link_to mentors_path, class: 'mdl-navigation__link' do %>
                        <i class="mdl-color-text--blue-grey-400 material-icons" role="presentation">person</i>Mentors</a>
                <% end %>
                <%= link_to groups_index_path, class: 'mdl-navigation__link' do %>
                    <i class="mdl-color-text--blue-grey-400 material-icons" role="presentation">group</i>Groups</a>
            <% end %>
            <%= link_to workshops_index_path, class: 'mdl-navigation__link' do %>
                <i class="mdl-color-text--blue-grey-400 material-icons" role="presentation">present_to_all</i>Workshop Presentations</a>
        <% end %>
        <%= link_to resources_index_path, class: 'mdl-navigation__link' do %>
            <i class="mdl-color-text--blue-grey-400 material-icons" role="presentation">book</i>Resources</a>
    <% end %>
    <%= link_to updates_index_path, class: 'mdl-navigation__link' do %>
        <i class="mdl-color-text--blue-grey-400 material-icons" role="presentation">flag</i>Updates</a>
<% end %>
<%= link_to posts_path, class: 'mdl-navigation__link' do %>
    <i class="mdl-color-text--blue-grey-400 material-icons" role="presentation">message</i>Message Board</a>
<% end %>
</nav>
        </div>
    <% end %>
    <main class="mdl-layout__content mdl-color--grey-100">
        <div class="page-container">
            <div id="flash">
                <% flash.each do |key, value| %>
                    <div id="card-alert" class="card green custom-flash">
                        <div class="card-content white-text">
                            <% if key != "timedout" %>
                                <p><%= value %></p>
                            <% end %>
                        </div>
                    </div>
                <% end %>
            </div>
            <% if logged_in? && @current_user.admin? %>
                <%= render 'pages/admin_panel' %>
            <% end %>
            <%= yield %>
        </div>
    </main>

    <script src="https://code.getmdl.io/1.3.0/material.min.js"></script>
    <script>
        $(document).ready(function() {
            setTimeout(function() {
                $('#flash').remove();
            }, 5000);
        })
    </script>
</body>

</html>