config/routes.rb
Rails.application.routes.draw do
  # namespace :admin do
  # get 'mentors/index'
  # end

  # namespace :admin do
  # get 'mentors/show'
  # end

  # namespace :admin do
  # get 'mentors/new'
  # end

  # namespace :admin do
  # get 'mentors/create'
  # end

  # namespace :admin do
  # get 'mentors/edit'
  # end

  # namespace :admin do
  # get 'mentors/update'
  # end

  # namespace :admin do
  # get 'mentors/archive_mentor'
  # end

  # sessions
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'

  root to: 'pages#index'

  get 'helps/index'

  get 'message_boards/index'

  get 'updates/index'

  get 'resources/index'

  get '/mentors', to: 'mentors#index'

  get 'students/index'

  get 'students/create'

  get 'students/edit'

  get '/home', to: 'pages#index'
  get 'users/new', to: 'users#new'

  resources :cohorts, :users

  namespace :admin do
    resources :users
    resources :cohorts
    resources :groups
    post '/archive/:id', to: 'users#archive_student', as: 'archive'
    get '/getStudentsByGroup/:id', to: 'groups#students_by_group'
  end

  # mentors
  get '/mentors', to: 'mentors#index'

  # get  '/signup',  to: 'users#new'
  # post '/signup', to: 'users#create'

  # students
  resources :posts
  resources :students
  resource :calendar, only: [:show], controller: :calendar
  get 'calendar/show'

  # groups
  get 'groups/index'
  get 'groups/show/:id', to: 'groups#show'

  # Calendar
  # resources :calendar, only: [:show], controller: :calendar
  resources :events

  # workshop
  get 'workshops/index'
  get '/workshops/:id', to: 'workshops#show', as: 'workshop'

  # reset password
  resources :password_resets, only: %i[new update]
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id               :bigint(8)        not null, primary key
#  first_name       :string
#  last_name        :string
#  email            :string
#  password_digest  :string
#  created_at       :datetime         not null
#  updated_at       :datetime         not null
#  role             :string
#  reset_digest     :string
#  reset_sent_at    :datetime
#  archive          :boolean          default(FALSE)
#  user_information :jsonb            not null
#  group_id         :integer
#

class User < ApplicationRecord
  has_secure_password
  attr_accessor :reset_token
  store_accessor :user_information, :avatar, :phone, :school, :grade
  before_save { self.email = email.downcase }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i.freeze

  validates :first_name, presence: true, length: { maximum: 50 }
  validates :last_name, presence: true, length: { maximum: 50 }
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
  # TODO: the way I am creating passwords, I will need to validate this a different way
  # or figure out a work around for the archive_user
  validates :password, presence: true, length: { minimum: 6 }, on: %i[create]
  # validates :password, presence: true, length: { minimum: 6 }, on: %i[create update]

  has_many :posts, class_name: 'Post', foreign_key: :auther_id, primary_key: :id
  has_and_belongs_to_many :cohorts
  # NOTES this could change to has_many
  belongs_to :group, optional: true

  def user_tag
    name.downcase.insert(0, '@')
  end

  def role?
    # TODO: not sure this is the best right now
    role
  end

  def student?
    role == 'student'
  end

  def admin?
    role == 'admin'
  end

  def mentor?
    role == 'mentor'
  end

  def name
    "#{first_name.capitalize} #{last_name.capitalize}"
  end

  def group_name
    group && group.name
  end

  def archived?
    archive == true
  end

  def login_count
    user_information['sign_in_count']
  end

  def remove_from_group
    self.group_id = nil
  end

  # Returns a random token
  # def User.new_token
  #   SecureRandom.urlsafe_base64
  # end

  # Sets the password reset attributes.
  # def create_reset_digest
  #   self.reset_token = User.new_token
  #   update_attribute(:reset_digest,  User.digest(reset_token))
  #   update_attribute(:reset_sent_at, Time.zone.now)
  # end

  # Sends password reset email.
  # def send_password_reset_email
  #   UserMailer.password_reset(self).deliver_now
  # end

  # Returns true if a password reset has expired.
  # def password_reset_expired?
  #   reset_sent_at < 2.hours.ago
  # end
end

app/controllers/admin/users_controller.rb
# NOTES: this controller handles the creation of both sutdent AND metnors

class Admin::UsersController < Admin::ApplicationController
  include ApplicationHelper
  include UsersHelper
  respond_to :html, :json

  before_action :admin_authorize
  before_action :set_user, only: %i[
    show
    archive_student
    edit
    update
  ]

  def show
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @user }
    end
  end

  def index
    if params['user'] == 'student' && Cohort.all.empty?
      redirect_to admin_cohorts_path,
                  notice: 'Must create a Cohort before you can add students'
    end
    # I need to change this table too has_many through. I think that will solve
    # my issues with group_by
    # NOTES can I do all this modifications in serializor
    # t.name.split(' ').join('_').to_sym
    # FIXME OMG I want to puke on the below line of code
    # this is such HACK
    # students = User.all
    # @students = students.select { |student| student.student? &&
    # !student.archived? }
    # @cohorts = Cohort.all.map { |x| {x.name => x.users} }.flatten
    # Cohort.all.group_by { |x| x.collect(&:users) }
    # @cohorts = @cohorts_groups.group_by { |k| {k.name => k.users} }
    # I want a key with cohort name with the value being the students that belong
    # to that cohort (should be easy????)
    if params[:cohortName]
      @students = Cohort.find_by_name(params[:cohortName].downcase).users
      # TODO: do NOT want to send password along
      return render json: @students
    end

    if params[:user] == 'student'
      @student = true
      @page_title = 'Students'
      @button_title = 'Add Student'
      @form = 'students_index'
      # FIXME: this is SO ugly.. wow...
      @cohorts_groups = Cohort.all

      @cohorts = Cohort.all.collect(&:users)
    end

    if params[:user] == 'mentor'
      @mentor = true
      @page_title = 'Mentors'
      @button_title = 'Add Mentor'
      @form = 'mentors_index'
      # FIXME: this is SO ugly.. wow...
      @cohorts_groups = Cohort.all

      @mentors = User.all.select(&:mentor?)
    end

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @cohorts }
    end
  end

  def new
    @user = User.new
    @user.role = params[:user]
    if params[:user] == 'mentor'
      @page_title = 'Add a Mentor'
      @mentor = User.new
      @form = 'mentor_form'
    end

    if params[:user] == 'student'
      @page_title = 'Add a Student'
      @student = User.new
      @form = 'student_form'
    end

    # NOTES I think it would be cool if I could figure out how to render from here
    # always get missing template _application
    # if params[:user] == 'mentor'
    # #render :partial => 'mentor_form', :layout => 'application'
    # end
  end

  def create
    user_password = generate_password
    params[:user][:password] = user_password
    params[:user][:password_confirmation] = user_password
    @user = User.new(user_params)
    if @user.save
      @user.cohort_ids = params['user']['cohort_ids']
      UserNotifierMailer.send_signup_email(@user).deliver
      flash[:success] = "#{@user.name.capitalize} has been added"
    else
      # TODO: this is such a hack... fix this
      flash[:error] = @user.errors.full_messages.to_sentence
    end
    redirect_to admin_users_path(user: @user.role)
  end

  def edit
    if @user.mentor?
      @page_title = 'Edit a Mentor'
      @form = 'mentor_form'
    end

    if @user.student?
      @page_title = 'Edit a Student'
      @form = 'student_form'
    end
  end

  def update
    # NOTE Currently student can only belong to ONE cohort
    remove_student_from_cohort(@user) if params['user']['cohort_ids'].present?

    if @user.update_attributes(user_params)
      flash[:success] = "#{@user.name.capitalize} has been updated"
      redirect_to admin_users_path(user: @user.role)
    else
      flash[:error] = 'Something went wrong'
      render 'edit'
    end
  end

  # FIXME: this should be archive_user
  def archive_student
    @user.archive = true
    if @user.save(validate: false)
      flash[:success] = "#{@user.name.capitalize} has been Archived"
      redirect_to admin_users_path(user: @user.role)
    else
      flash[:error] = 'Something went wrong'
      render 'edit'
    end
  end

  private

  def user_params
    # FIXME: I can set stor-attr
    params.require(:user).permit(:first_name,
                                 :last_name,
                                 :email,
                                 :password,
                                 :password_confirmation,
                                 :role,
                                 :cohort_ids,
                                 user_information: [
                                   :avatar,
                                   :phone,
                                   :school,
                                   :grade,
                                   :company,
                                   :specialty,
                                   :compnay_logo,
                                   social_media: %i[
                                     instagram
                                     linkedin
                                     twitter
                                     facebook
                                   ]
                                 ])
  end

  def set_user
    @user = User.find_by_id(params[:id])
    cohorts = @user.cohorts.pluck(:name)
    # TODO: I feel like there is somethin not right here. I dont think I should
    # have to set user_information like this user_information = {}
    cohorts.empty? ? @user.user_information = { cohorts: ['All Cohorts'] } :
      @user.user_information['cohorts'] = cohorts
  end

  def remove_student_from_cohort(user)
    user_cohort = user.cohorts
    user.cohorts.delete(user_cohort)
    user.cohort_ids = params['user']['cohort_ids']
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  respond_to :html, :json
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/users_helper.rb
module UsersHelper
  require 'securerandom'
  def generate_password
    SecureRandom.hex(4)
  end
end

app/views/admin/users/_mentor_form.html.erb
<div class="card">
    <div class="card-content">
        <% if @user.errors.any? %>
            <ul class="Signup_Errors">
                <% for message_error in @user.errors.full_messages %>
                    <li class="alert alert-warning"><%= message_error %></li>
                <% end %>
            </ul>
        <% end %>
        <span class='card-title'><%= @page_title %></span>

        <%#= form_for @user, url: password_reset_path(@user) do |f| %>
        <%= form_for [:admin, @user] do |f| %>
            <div class="row">
                <div class="input-field col s12 m6">
                    <%= f.label :first_name %>
                    <%= f.text_field :first_name, class: '' %>
                </div>
                <div class="input-field col s12 m6">
                    <%= f.label :last_name %>
                    <%= f.text_field :last_name, class: '' %>
                </div>
            </div>
            <div class="row">
                <div class="input-field col s12 m6">
                    <%= f.label :email, "Email" %>
                    <%= f.text_field :email, class: '' %>
                </div>
            </div>
            <br>
            <div class="row">
                <div class="input-field col s12 m6">
                    <div class="input-field col s12">
                    <%= collection_select(:user, :cohort_ids, Cohort.all, :id, :name, {}, { :multiple => true } )%>
                        <%#= f.select :cohort_ids, Cohort.all.map { |p| [ p.name, p.id ] }, {:include_blank => true } %>
                        <%#= options_for_select Cohort.all.map { |p| [ p.name, p.id ] } %>
                        <label>Cohort Seletcion</label>
                    </div>
                </div>
                <div class="input-field col s12 m6">
                    <%= f.label :role, "Role" %>
                    <%= f.text_field :role, class: '', value: 'mentor' %>
                </div>
            </div>
                <%= f.fields_for :user_information do |info| %>
                    <div class="row">
                        <div class="input-field col s12 m3">
                            <%= info.label :avatar %>
                            <%= info.text_field :avatar, class: '', placeholder: 'coming soon' %>
                        </div>
                        <div class="input-field col s12 m3">
                            <%= info.label :phone %>
                            <%= info.text_field :phone, class: '', value: @user.user_information["phone"] %>
                        </div>
                        <div class="input-field col s12 m3">
                            <%= info.label :company %>
                            <%= info.text_field :company, class: '', value: @user.user_information["company"] %>
                        </div>
                        <div class="input-field col s12 m3">
                            <%= info.label :specialty %>
                            <%= info.text_field :specialty, class: '', value: @user.user_information["specialty"] %>
                        </div>
                    </div>
                    <div class="row">
                        <%= info.fields_for :social_media do |media| %>
                            <div class="input-field col s12 m3">
                                <%= media.label :linkedin %>
                                <%= media.text_field :linkedin, class: '', value: @user.user_information.try(:[], "social_media").try(:[], "linkedin") || "https://" %>
                            </div>
                        <% end %>
                    </div>
                <% end %>

            <div class="card-action">
                <div class='right-align'>
                    <%= f.submit 'Submit', class: 'btn light-green accent-4' %>
                    <%= link_to "Cancel", admin_users_path(user: @user.role), class: 'btn red' %>
                </div>
            </div>
        <% end %>
    </div>
</div>

app/views/admin/users/_mentors_index.html.erb
<!-- Mentors Table -->
<% if @mentors.empty? %>
    <p>No mentors</p>
<% else %>
    <table class='highlight responsive-table'>
        <thead>
            <tr>
                <th></th>
                <th>Name</th>
                <th>Company</th>
                <th>Specialty</th>
                <th>Email</th>
                <th>Phone</th>
                <th>LinkedIn</th>
                <th>Actions</th>
            </tr>
        </thead>
        <% @mentors.each do |mentor| %>
            <tbody>
                <!-- FIXME this is so ugly.. fix this, this payload should already not
                include archived users -->
                <tr>
                    <% if mentor.user_information.try(:[], 'avatar').present? %>
                        <td><%= image_tag mentor.user_information['avatar'],
                            class: 'avatar-small z-depth-1' %></td>
                    <% else %>
                        <td><%= image_tag 'user_avatar_2.png',
                            class: 'avatar-small z-depth-1' %></td>
                    <% end %>
                    <td><%= mentor.name %></td>
                    <td><%= mentor.user_information['company'] %></td>
                    <td><%= mentor.user_information['specialty'] %></td>
                    <td><a href="mailto:<%= mentor['email'] %>"><%= mentor["email"] %></td>
                        <td><%= mentor.user_information['phone'] %></td>
                        <td>
                            <div id="admin-social-media-container">
                                <% if mentor.user_information.try(:[], 'social_media').present? %>
                                    <% mentor.user_information["social_media"].each do |media| %>
                                        <%= get_social_media(media) %>
                                    <% end %>
                                <% end %>
                            </div>
                        </td>
                        <td>

                            <%= link_to edit_admin_user_path(mentor) do %>
                                <i class="material-icons green z-depth-1 small-button">edit</i>
                            <% end %>
                            <%= link_to admin_archive_path(mentor),
                                method: :student_archive,
                                data: { confirm: "Are you sure about archive #{mentor.first_name}" } do %>
                                <i class="material-icons red z-depth-1 small-button">delete_forever</i>
                            <% end %>
                            <i onclick="displayStudentInformation('<%= mentor.id %>');" class="material-icons blue z-depth-1 small-button">expand_more</i>
                        </td>
                    </tr>
                    <tr id='<%= mentor.id %>'class='student-info'
                        style='display: none'>
                    </tr>
                <% end %>
            </tbody>
        </table>
    <% end %>

app/views/admin/users/_student_form.html.erb
<div class="card">
    <div class="card-content">
        <% if @user.errors.any? %>
            <ul class="Signup_Errors">
                <% for message_error in @user.errors.full_messages %>
                    <li class="alert alert-warning"><%= message_error %></li>
                <% end %>
            </ul>
        <% end %>
        <span class='card-title'><%= @page_title %></span>
        <%= form_for [:admin, @user] do |f| %>
            <div class="row">
                <div class="input-field col s12 m6">
                    <%= f.label :first_name %>
                    <%= f.text_field :first_name, class: '' %>
                </div>
                <div class="input-field col s12 m6">
                    <%= f.label :last_name %>
                    <%= f.text_field :last_name, class: '' %>
                </div>
            </div>
            <div class="row">
                <div class="input-field col s12 m6">
                    <%= f.label :email, "Email" %>
                    <%= f.text_field :email, class: '' %>
                </div>
            </div>
            <br>
            <div class="row">
                <div class="input-field col s12 m6">
                    <div class="input-field col s12">
                        <%= f.select :cohort_ids, Cohort.all.map { |p| [ p.name, p.id ] } %>
                        <label>Cohort Seletcion</label>
                    </div>
                </div>
                <div class="input-field col s12 m6">
                    <%= f.label :role, "Role" %>
                    <%= f.text_field :role, class: '', value: 'student' %>
                </div>
            </div>
                <%= f.fields_for :user_information do |info| %>
                    <div class="row">
                        <div class="input-field col s12 m4">
                            <%= info.label :avatar %>
                            <%= info.text_field :avatar, class: '', placeholder: 'coming soon' %>
                        </div>
                        <div class="input-field col s12 m4">
                            <%= info.label :phone %>
                            <%= info.text_field :phone, class: '', value: @user.user_information["phone"] %>
                        </div>
                        <div class="input-field col s12 m4">
                            <%= info.label :school %>
                            <%= info.text_field :school, class: '', value: @user.user_information["school"] %>
                        </div>
                    </div>
                    <div class="row">
                        <div class="input-field col s12 m3">
                            <%= info.label :grade %>
                            <%= info.text_field :grade, class: '', value: @user.user_information["grade"] %>
                        </div>
                    </div>
                    <div class="row">
                        <%= info.fields_for :social_media do |media| %>
                            <div class="input-field col s12 m3">
                                <%= media.label :instagram %>
                                <%= media.text_field :instagram, class: '', placeholder: 'https://www.instagram.com', value: @user.user_information.try(:[], "social_media").try(:[], "instagram") %>
                            </div>
                            <div class="input-field col s12 m3">
                                <%= media.label :linkedin %>
                                <%= media.text_field :linkedin, class: '', placeholder: 'https://www.linkedin.com', value: @user.user_information.try(:[], "social_media").try(:[], "linkedin") %>
                            </div>
                            <div class="input-field col s12 m3">
                                <%= media.label :twitter %>
                                <%= media.text_field :twitter, class: '', placeholder: 'https://www.twitter.com', value: @user.user_information.try(:[], "social_media").try(:[], "twitter") %>
                            </div>
                            <div class="input-field col s12 m3">
                                <%= media.label :facebook %>
                                <%= media.text_field :facebook, class: '', placeholder: 'https://www.facebook.com', value: @user.user_information.try(:[], "social_media").try(:[], "facebook") %>
                            </div>
                        <% end %>
                    </div>
                <% end %>

            <div class="card-action">
                <div class='right-align'>
                    <%= f.submit 'Submit', class: 'btn light-green accent-4' %>
                    <%= link_to "Cancel", admin_users_path(user: @user.role), class: 'btn red' %>
                </div>
            </div>
        <% end %>
    </div>
</div>

app/views/admin/users/_students_index.html.erb
<!-- Student Table -->
<% @cohorts_groups.each do |cohort| %>
    <div class='chip z-depth-1'
        style='background-color: <%= cohort.settings["color"].downcase %>'>
        <%= cohort.name %>
        <i onclick="toggle_cohort_div('<%= cohort.name.split(' ').join('-') %>');" class="close material-icons">close</i>
    </div>
<% end %>

<div id="clear-filter-chip" onclick='clear_filter()' class='chip z-depth-1 clear-chip'>Clear Filter</div>

<div class="mb-m"></div>

<% @cohorts.each do |cohort| %>
    <div class="card">
        <table id='<%= cohort.empty? ? 'empty' :
            cohort.first.cohorts[0].name.split(' ').join('-') %>'
            class='highlight responsive-table'>
            <thead>
                <tr>
                    <!-- FIXME OMG I want to puke on the below line of code -->
                    <th style='color: <%= cohort.empty? ? '#ccc' :
                        cohort.first.cohorts[0].settings["color"]
                        .downcase %>'><%= cohort.empty? ? 'No students' :
                    cohort.first.cohorts[0].name %></th>
                <th>Name</th>
                <th>Email</th>
                <th>Socail Media</th>
                <th>Actions</th>
            </tr>
        </thead>
        <tbody>
            <% cohort.each do |student| %>
                <!-- FIXME this is so ugly.. fix this, this payload should already not
                include archived users -->
                <% if !student.archive %>
                    <tr>
                        <% if student.user_information.try(:[], 'avatar').present? %>
                            <td><%= image_tag student.user_information['avatar'],
                                class: 'avatar-small z-depth-1' %></td>
                        <% else %>
                            <td><%= image_tag 'user.jpg',
                                class: 'avatar-small z-depth-1' %></td>
                        <% end %>
                        <td><%= student.name %></td>
                        <td><a href="mailto:<%= student['email'] %>"><%= student["email"] %></td>
                            <td>
                                <div id="admin-social-media-container">
                                    <% if student.user_information.try(:[], 'social_media').present? %>
                                        <% student.user_information["social_media"].each do |media| %>
                                            <%= get_social_media(media) %>
                                        <% end %>
                                    <% end %>
                                </div>
                            </td>
                            <td>

                                <%= link_to edit_admin_user_path(student) do %>
                                    <i class="material-icons green z-depth-1 small-button">edit</i>
                                <% end %>
                                <%= link_to admin_archive_path(student),
                                    method: :student_archive,
                                    data: { confirm: "Are you sure about archive #{student.first_name}" } do %>
                                    <i class="material-icons red z-depth-1 small-button">delete_forever</i>
                                <% end %>
                                <i onclick="displayStudentInformation('<%= student.id %>');" class="material-icons blue z-depth-1 small-button">expand_more</i>
                            </td>
                        </tr>
                        <tr id='<%= student.id %>'class='student-info'
                            style='display: none'>
                        </tr>

                    <% end %>
                <% end %>
            </tbody>
        </table>
    </div>
<% end %>

app/views/admin/users/_user_form.html.erb
<div class="card">
    <div class="card-content">
        <% if @student.errors.any? %>
            <ul class="Signup_Errors">
                <% for message_error in @student.errors.full_messages %>
                    <li class="alert alert-warning"><%= message_error %></li>
                <% end %>
            </ul>
        <% end %>
        <span class='card-title'><%= @page_title %></span>
        <%= form_for [:admin, @student] do |f| %>
            <div class="row">
                <div class="input-field col s12 m6">
                    <%= f.label :first_name %>
                    <%= f.text_field :first_name, class: '' %>
                </div>
                <div class="input-field col s12 m6">
                    <%= f.label :last_name %>
                    <%= f.text_field :last_name, class: '' %>
                </div>
            </div>
            <div class="row">
                <div class="input-field col s12 m6">
                    <%= f.label :password %>
                    <%= f.password_field :password, class: '' %>
                </div>
                <div class="input-field col s12 m6">
                    <%= f.label :password_confirmation, "Confirmation" %>
                    <%= f.password_field :password_confirmation, class: '' %>
                </div>
                <div class="input-field col s12 m6">
                    <%= f.label :email, "Email" %>
                    <%= f.text_field :email, class: '' %>
                </div>
            </div>
            <br>
            <div class="row">
                <div class="input-field col s12 m6">
                    <div class="input-field col s12">
                        <%= f.select :cohort_ids, Cohort.all.map { |p| [ p.name, p.id ] } %>
                        <label>Cohort Seletcion</label>
                    </div>
                </div>
                <div class="input-field col s12 m6">
                    <%= f.label :role, "Role" %>
                    <%= f.text_field :role, class: '', value: 'student' %>
                </div>
            </div>
                <%= f.fields_for :user_information do |info| %>
                    <div class="row">
                        <div class="input-field col s12 m4">
                            <%= info.label :avatar %>
                            <%= info.text_field :avatar, class: '', placeholder: 'coming soon' %>
                        </div>
                        <div class="input-field col s12 m4">
                            <%= info.label :phone %>
                            <%= info.text_field :phone, class: '', value: @student.user_information["phone"] %>
                        </div>
                        <div class="input-field col s12 m4">
                            <%= info.label :school %>
                            <%= info.text_field :school, class: '', value: @student.user_information["school"] %>
                        </div>
                    </div>
                    <div class="row">
                        <div class="input-field col s12 m3">
                            <%= info.label :grade %>
                            <%= info.text_field :grade, class: '', value: @student.user_information["grade"] %>
                        </div>
                    </div>
                    <div class="row">
                        <%= info.fields_for :social_media do |media| %>
                            <div class="input-field col s12 m3">
                                <%= media.label :instagram %>
                                <%= media.text_field :instagram, class: '', value: @student.user_information.try(:[], "social_media").try(:[], "instagram") || "https://" %>
                            </div>
                            <div class="input-field col s12 m3">
                                <%= media.label :linkedin %>
                                <%= media.text_field :linkedin, class: '', value: @student.user_information.try(:[], "social_media").try(:[], "linkedin") || "https://" %>
                            </div>
                            <div class="input-field col s12 m3">
                                <%= media.label :twitter %>
                                <%= media.text_field :twitter, class: '', value: @student.user_information.try(:[], "social_media").try(:[], "twitter") || "https://" %>
                            </div>
                            <div class="input-field col s12 m3">
                                <%= media.label :facebook %>
                                <%= media.text_field :facebook, class: '', value: @student.user_information.try(:[], "social_media").try(:[], "facebook") || "https://" %>
                            </div>
                        <% end %>
                    </div>
                <% end %>

            <div class="card-action">
                <div class='right-align'>
                    <%= f.submit 'Submit', class: 'btn light-green accent-4' %>
                    <%= link_to "Cancel", admin_users_path, class: 'btn red' %>
                </div>
            </div>
        <% end %>
    </div>
</div>

app/views/admin/users/edit.html.erb
<%= render @form %>

app/views/admin/users/index.html.erb
<%= render @form %>

app/views/admin/users/new.html.erb
<%= render @form %>